name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install prereqs
      run:  |
        sudo apt update
        sudo apt install grub-pc-bin nasm mtools qemu-utils xorriso wget unzip libgmp3-dev libmpc-dev	libmpfr-dev	
      shell: bash

    - name: Create toolchain
      run: ./src/scripts/make_toolchain.sh --parallel_build -s ~/sysroot --package ~/toolchain.tar.xz
      shell: bash

    - name: Compile kernel
      run: make kernel

    - name: Create ISO
      run: make iso
      
    - name: Create hdfile
      run: make sorhd
      
    # - name: Upload compiled toolchain
    #   uses: actions/upload-artifact@v2
    #   with: 
    #     name: sectoros_toolchain
    #     path: ~/toolchain.tar.xz

    - name: Upload kernel
      uses: actions/upload-artifact@v2
      with: 
        name: kernel
        path: SectorOS-RW4.elf

    - name: Upload ISO
      uses: actions/upload-artifact@v2
      with: 
        name: iso
        path: SectorOS-RW4.iso

    - name: Upload HDIMAGE
      uses: actions/upload-artifact@v2
      with: 
        name: hdimage
        path: sorhd
